---
- name: Configurar sudo sin contraseña para el grupo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%<Nombre-Grupo>'
    line: '%<Nombre-Grupo> ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

